/* eslint-disable */
// this file is autogenerated, run python scripts/update-telemetry-schema.py to regenerate after yaml file was changed
const telemetrySchema = {
    "pings": [
        "custom"
    ],
    "metrics": {
        "metadata": {
            "from_lang": {
                "type": "string",
                "send_in_pings": [
                    "custom"
                ]
            },
            "to_lang": {
                "type": "string",
                "send_in_pings": [
                    "custom"
                ]
            },
            "firefox_client_id": {
                "type": "string",
                "send_in_pings": [
                    "custom"
                ]
            },
            "extension_version": {
                "type": "string",
                "send_in_pings": [
                    "custom"
                ]
            },
            "extension_build_id": {
                "type": "string",
                "send_in_pings": [
                    "custom"
                ]
            },
            "bergamot_translator_version": {
                "type": "string",
                "send_in_pings": [
                    "custom"
                ]
            },
            "system_memory": {
                "type": "quantity",
                "send_in_pings": [
                    "custom"
                ]
            },
            "cpu_count": {
                "type": "quantity",
                "send_in_pings": [
                    "custom"
                ]
            },
            "cpu_cores_count": {
                "type": "quantity",
                "send_in_pings": [
                    "custom"
                ]
            },
            "cpu_vendor": {
                "type": "string",
                "send_in_pings": [
                    "custom"
                ]
            },
            "cpu_family": {
                "type": "quantity",
                "send_in_pings": [
                    "custom"
                ]
            },
            "cpu_model": {
                "type": "quantity",
                "send_in_pings": [
                    "custom"
                ]
            },
            "cpu_stepping": {
                "type": "quantity",
                "send_in_pings": [
                    "custom"
                ]
            },
            "cpu_l2_cache": {
                "type": "quantity",
                "send_in_pings": [
                    "custom"
                ]
            },
            "cpu_l3_cache": {
                "type": "quantity",
                "send_in_pings": [
                    "custom"
                ]
            },
            "cpu_speed": {
                "type": "quantity",
                "send_in_pings": [
                    "custom"
                ]
            },
            "cpu_extensions": {
                "type": "string",
                "send_in_pings": [
                    "custom"
                ]
            }
        },
        "performance": {
            "total_usage_time": {
                "type": "timespan",
                "send_in_pings": [
                    "custom"
                ]
            },
            "full_page_translated_time": {
                "type": "timespan",
                "send_in_pings": [
                    "custom"
                ]
            },
            "full_page_translated_wps": {
                "type": "quantity",
                "send_in_pings": [
                    "custom"
                ]
            },
            "model_download_time_num": {
                "type": "timespan",
                "send_in_pings": [
                    "custom"
                ]
            },
            "model_load_time_num": {
                "type": "timespan",
                "send_in_pings": [
                    "custom"
                ]
            },
            "translation_engine_time": {
                "type": "timespan",
                "send_in_pings": [
                    "custom"
                ]
            },
            "translation_engine_wps": {
                "type": "quantity",
                "send_in_pings": [
                    "custom"
                ]
            },
            "word_count": {
                "type": "quantity",
                "send_in_pings": [
                    "custom"
                ]
            },
            "word_count_visible_in_viewport": {
                "type": "quantity",
                "send_in_pings": [
                    "custom"
                ]
            },
            "translation_quality": {
                "type": "string",
                "send_in_pings": [
                    "custom"
                ]
            }
        },
        "infobar": {
            "displayed": {
                "type": "event",
                "send_in_pings": [
                    "custom"
                ]
            },
            "closed": {
                "type": "event",
                "send_in_pings": [
                    "custom"
                ]
            },
            "translate": {
                "type": "event",
                "send_in_pings": [
                    "custom"
                ]
            },
            "never_translate_lang": {
                "type": "event",
                "send_in_pings": [
                    "custom"
                ]
            },
            "never_translate_site": {
                "type": "event",
                "send_in_pings": [
                    "custom"
                ]
            },
            "not_now": {
                "type": "event",
                "send_in_pings": [
                    "custom"
                ]
            },
            "change_lang": {
                "type": "event",
                "send_in_pings": [
                    "custom"
                ]
            },
            "outbound_checked": {
                "type": "event",
                "send_in_pings": [
                    "custom"
                ]
            },
            "outbound_unchecked": {
                "type": "event",
                "send_in_pings": [
                    "custom"
                ]
            },
            "outbound_enabled": {
                "type": "boolean",
                "send_in_pings": [
                    "custom"
                ]
            }
        },
        "service": {
            "not_supported": {
                "type": "counter",
                "send_in_pings": [
                    "custom"
                ]
            },
            "lang_mismatch": {
                "type": "counter",
                "send_in_pings": [
                    "custom"
                ]
            }
        },
        "errors": {
            "translation": {
                "type": "counter",
                "send_in_pings": [
                    "custom"
                ]
            },
            "marian": {
                "type": "counter",
                "send_in_pings": [
                    "custom"
                ]
            },
            "memory": {
                "type": "counter",
                "send_in_pings": [
                    "custom"
                ]
            },
            "model_download": {
                "type": "counter",
                "send_in_pings": [
                    "custom"
                ]
            },
            "engine_download": {
                "type": "counter",
                "send_in_pings": [
                    "custom"
                ]
            },
            "engine_load": {
                "type": "counter",
                "send_in_pings": [
                    "custom"
                ]
            },
            "model_load": {
                "type": "counter",
                "send_in_pings": [
                    "custom"
                ]
            }
        },
        "forms": {
            "displayed": {
                "type": "event",
                "send_in_pings": [
                    "custom"
                ]
            },
            "hidden": {
                "type": "event",
                "send_in_pings": [
                    "custom"
                ]
            },
            "field_count": {
                "type": "quantity",
                "send_in_pings": [
                    "custom"
                ]
            },
            "character_count": {
                "type": "quantity",
                "send_in_pings": [
                    "custom"
                ]
            },
            "word_count": {
                "type": "quantity",
                "send_in_pings": [
                    "custom"
                ]
            }
        }
    }
}