name: Artifact Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - name: Install dependencies
        run: npm install
      - name: Run linter
        run: npm run lint:js
      - name: Build XPI
        run: npm run build
      - uses: actions/upload-artifact@v2
        with:
          name: Extension-XPI
          path: web-ext-artifacts/firefox_translations-*.zip
