name: End-to-End Tests on esr102
on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 1 * * *'
  pull_request:
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '17.x'
      - run: brew unlink python@3.10
      - run: brew install python@3.9
      - run: npm install
      - run: brew install git-cinnabar
      - name: Run e2e test on esr102
        run: python3 scripts/tests/e2e-tests-esr102.py
